/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ReferralLink = IDL.Record({
  'id' : IDL.Nat,
  'tanggalDibuat' : Time,
  'kode' : IDL.Text,
  'deskripsi' : IDL.Opt(IDL.Text),
  'pemilik' : IDL.Principal,
  'urlTujuan' : IDL.Text,
  'jumlahKlik' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'buatLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [ReferralLink],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKodeLink' : IDL.Func([IDL.Text], [ReferralLink], ['query']),
  'getLinkByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReferralLink)],
      ['query'],
    ),
  'getLinksByCurrentUser' : IDL.Func([], [IDL.Vec(ReferralLink)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hapusLink' : IDL.Func([IDL.Text], [], []),
  'incrementClickCount' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'redirectLinkAndCount' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLinkData' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [ReferralLink],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReferralLink = IDL.Record({
    'id' : IDL.Nat,
    'tanggalDibuat' : Time,
    'kode' : IDL.Text,
    'deskripsi' : IDL.Opt(IDL.Text),
    'pemilik' : IDL.Principal,
    'urlTujuan' : IDL.Text,
    'jumlahKlik' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'buatLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [ReferralLink],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKodeLink' : IDL.Func([IDL.Text], [ReferralLink], ['query']),
    'getLinkByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReferralLink)],
        ['query'],
      ),
    'getLinksByCurrentUser' : IDL.Func([], [IDL.Vec(ReferralLink)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hapusLink' : IDL.Func([IDL.Text], [], []),
    'incrementClickCount' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'redirectLinkAndCount' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLinkData' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [ReferralLink],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };