/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ReferralLink {
  'id' : bigint,
  'tanggalDibuat' : Time,
  'kode' : string,
  'deskripsi' : [] | [string],
  'pemilik' : Principal,
  'urlTujuan' : string,
  'jumlahKlik' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'buatLink' : ActorMethod<[string, string, [] | [string]], ReferralLink>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKodeLink' : ActorMethod<[string], ReferralLink>,
  'getLinkByOwner' : ActorMethod<[Principal], Array<ReferralLink>>,
  'getLinksByCurrentUser' : ActorMethod<[], Array<ReferralLink>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hapusLink' : ActorMethod<[string], undefined>,
  'incrementClickCount' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'redirectLinkAndCount' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLinkData' : ActorMethod<
    [string, [] | [string], [] | [string]],
    ReferralLink
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];